const doctor1 = {
  id: "digimed_NAMNT",
  partnerId: "digimed",
  title: "Ngô Trung Nam",
  role: "BS CKII.",
  gender: "1",
  category: "doctor",
  desc: "",
  imageUrl:
    "https://cdn.medpro.vn/prod-partner/e4549b5e-15d0-4656-8157-ad47e269f42b-bs_ngaa_trung_nam.jpg",
  circleLogo: null,
  tags: [
    {
      id: "medpro_sanphukhoa",
      type: "subject",
      name: "Sản phụ khoa",
    },
  ],
  desc2: "Bác sĩ Chuyên Khoa",
  price: "200.000đ",
  priceDescription: null,
  treeId: "TELEMEDNOW",
  trees: [
    {
      treeId: "TELEMEDNOW",
      detailShiftId: null,
      doctorId: null,
      days: "LATER,2,3,4,5,6,7,CN",
    },
    {
      treeId: "TELEMED",
      detailShiftId: null,
      doctorId: null,
      days: "LATER,CN,2,3,4,5,6,7",
    },
  ],
  days: "Thứ 2,3,4,5,6,7,Chủ nhật,Hẹn khám",
  hospitalAddress: "Tư vấn Online qua App Medpro",
  treatments:
    "Phẫu thuật nội soi phụ khoa - Mổ thai ngoài nội soi - bóc u nang - u xơ - thu hẹp âm đạo - Tái tạo màng trinh; Điều trị lạc nội mạc tử cung; Siêu âm bơm nước buồng tử cung; Soi cổ tử cung; Y học bào thai - Thai kỳ nguy cơ cao - Thai chậm tăng trưởng - Thai nhẹ cân; Tiểu đường thai kỳ - Thai IVF - Song thai - Đa thai - Dọa sanh non - Khâu eo cổ tử cung - Chọc ối - Sinh thiết gai nhau;...",
  hospitals: [
    {
      id: "digimed",
      type: "hospital",
      name: "Bác sĩ Chuyên Khoa",
      address: "Tư vấn Online qua App Medpro",
      image:
        "https://cdn.medpro.vn/prod-partner/e4549b5e-15d0-4656-8157-ad47e269f42b-bs_ngaa_trung_nam.jpg",
      circleLogo: null,
      ctas: [
        {
          name: "Đặt lịch",
          partnerId: "digimed",
          treeId: "TELEMEDNOW",
          subjectId: null,
          serviceId: null,
          doctorId: "digimed_NAMNT",
          roomId: null,
        },
        {
          name: "Đặt lịch",
          partnerId: "digimed",
          treeId: "TELEMED",
          subjectId: null,
          serviceId: null,
          doctorId: "digimed_NAMNT",
          roomId: null,
        },
      ],
    },
  ],
  subjects: [
    {
      id: "digimed_SPK",
      type: "subject",
      name: "Sản phụ khoa",
      imageUrl:
        "https://cdn.medpro.vn/medpro-production/digimed/subjects/1747277067871-SAN_PHU_KHOA.png",
    },
  ],
  services: [
    {
      id: "5475687f30114a36b00563ad3e3e6c3c",
      type: "service",
      name: "Tư vấn online 01 lần",
      price: 200000,
      displayDetail: "",
      subjectNames: ["Sản phụ khoa"],
      popupContent:
        '<ul><li>Trong trường hợp bác sĩ bạn chọn không sắp xếp được giờ khám theo mong muốn, Medpro sẽ đề xuất và giới thiệu bác sĩ khác cùng chuyên khoa, hoặc bạn có thể sử dụng tính năng "Chat" để trao đổi và thống nhất giờ khám phù hợp với lịch làm việc của bác sĩ</li><li>Quý khách có thể chủ động liên hệ Bác sĩ qua tính năng Nhắn tin (Chat) trên phiếu Đặt Khám</li><li><span style="color:rgb(255,0,0);"><strong>Lưu ý:</strong>&nbsp;Thời gian hoạt động từ 06:00 đến 22:00 mỗi ngày</span></li></ul>',
      popupTitle: "Thông báo",
      popupContentUrl: null,
      ctas: [
        {
          name: "Đặt lịch",
          partnerId: "digimed",
          treeId: "TELEMED",
          subjectId: null,
          serviceId: "5475687f30114a36b00563ad3e3e6c3c",
          doctorId: "digimed_NAMNT",
          roomId: null,
        },
      ],
    },
    {
      id: "digimed_02",
      type: "service",
      name: "Tư vấn ngay online 01 lần",
      price: 200000,
      displayDetail: "",
      subjectNames: ["Sản phụ khoa"],
      popupContent:
        '<ul><li>Trong trường hợp bác sĩ bạn chọn không sắp xếp được giờ khám theo mong muốn, Medpro sẽ đề xuất và giới thiệu bác sĩ khác cùng chuyên khoa, hoặc bạn có thể sử dụng tính năng "Chat" để trao đổi và thống nhất giờ khám phù hợp với lịch làm việc của bác sĩ</li><li>Quý khách có thể chủ động liên hệ Bác sĩ qua tính năng Nhắn tin (Chat) trên phiếu Đặt Khám</li><li><span style="color:rgb(255,0,0);"><strong>Lưu ý:</strong>&nbsp;Thời gian hoạt động từ 06:00 đến 22:00 mỗi ngày</span></li></ul>',
      popupTitle: "Thông báo",
      popupContentUrl: null,
      ctas: [
        {
          name: "Đặt lịch",
          partnerId: "digimed",
          treeId: "TELEMEDNOW",
          subjectId: null,
          serviceId: "digimed_02",
          doctorId: "digimed_NAMNT",
          roomId: null,
        },
      ],
    },
  ],
  displayDetail: null,
  originalPrice: null,
  isDetailVisible: true,
  location: null,
  distance: null,
  sequenceDoctor: 1,
  priorityCategoryData: [
    {
      display: true,
      status: true,
      doctorId: "digimed_NAMNT",
      partnerId: "digimed",
      subjectId: null,
      serviceId: null,
      category: "doctor",
      order: 1,
      image:
        "https://cdn.medpro.vn/medpro-production/digimed/doctors/1760594995338.png",
      name: "Ngô Trung Nam",
      fromDate: null,
      toDate: null,
      type: "booking.telemed",
      treeId: "TELEMEDNOW",
      id: "68f1ffc3dfe487f807e09fca",
    },
    {
      display: true,
      status: true,
      doctorId: "digimed_NAMNT",
      partnerId: "digimed",
      subjectId: null,
      serviceId: null,
      category: "doctor",
      order: 1,
      image:
        "https://cdn.medpro.vn/medpro-production/digimed/doctors/1760594995338.png",
      name: "Ngô Trung Nam",
      fromDate: null,
      toDate: null,
      type: "booking.telemed",
      treeId: "TELEMED",
      id: "68f1ffe6dfe48734b2e09fd1",
    },
  ],
  promotePriceDescription: null,
  isPromote: null,
  cta: {
    name: "Đặt lịch",
    partnerId: "digimed",
    treeId: "TELEMEDNOW",
    subjectId: null,
    serviceId: null,
    doctorId: "digimed_NAMNT",
    roomId: null,
  },
  doctorDescription: {
    disabled: false,
    listBanner: [],
    workProcess:
      "<ul><li><strong>2006 – 2013: </strong>Bác sĩ điều trị chuyên ngành Sản phụ khoa tại Bệnh viện Phụ Sản Hùng Vương TPHCM</li><li><strong>2010 - 2024: </strong>Điều hành Phòng khám ngoài giờ BéBi tại Quận 10 - TPHCM</li><li><strong>2011 - nay: </strong>Bác sĩ điều trị chuyên ngành Sản phụ khoa và siêu âm chuyên sâu Sản phụ khoa tại Bệnh viện FV - Tp.HCM</li><li><strong>2013: </strong>Tham gia giảng dạy siêu âm sản phụ khoa lớp Chuyên khoa 1 Chẩn đoán hình ảnh tại Trường đại học y khoa Phạm Ngọc Thạch</li><li><strong>2017 - nay: </strong>Bác sĩ điều trị đơn vị Y học bào thai - chẩn đoán trước sinh, khoa Phụ Sản tại Bệnh viện Đại học y dược, cơ sở 1, Tp.HCM</li></ul>",
    educationProcess:
      "<ul><li><strong>1989 – 2000:</strong> Học phổ thông tại địa phương</li><li><strong>2000 – 2006:</strong> Học bác sĩ đa khoa tại Trung tâm Đào tạo và Bồi dưỡng Cán bộ Y tế, nay là Trường Đại học Y khoa Phạm Ngọc Thạch TPHCM</li><li><strong>2013 – 2015: </strong>Học chuyên khoa 1 - Chuyên ngành Sản phụ khoa tại Trường Đại học Y Dược TPHCM</li><li><strong>2021 - 2023:</strong> Học chuyên khoa 2 - Chuyên ngành Sản phụ khoa tại Trường Đại học Y khoa Phạm Ngọc Thạch TPHCM</li></ul>",
    isListing: false,
    selfIntroduction:
      '<p><span style="background-color:rgb(255,255,255);">Bác sĩ CKII Ngô Trung Nam là chuyên gia Sản Phụ khoa với hơn 18 năm kinh nghiệm tại các bệnh viện lớn như Hùng Vương, FV và Đại học Y Dược TP.HCM. Ông có chuyên môn sâu trong phẫu thuật nội soi phụ khoa, điều trị lạc nội mạc tử cung, y học bào thai và quản lý thai kỳ nguy cơ cao.</span></p><h3>Lĩnh vực lâm sàng chuyên sâu</h3><ul><li>Phẫu thuật nội soi phụ khoa - Mổ thai ngoài nội soi - bóc u nang - u xơ - thu hẹp âm đạo - Tái tạo màng trinh</li><li>Điều trị lạc nội mạc tử cung</li><li>Siêu âm bơm nước buồng tử cung</li><li>Soi cổ tử cung</li><li>Y học bào thai - Thai kỳ nguy cơ cao - Thai chậm tăng trưởng - Thai nhẹ cân - Tiểu đường thai kỳ - Thai IVF - Song thai - Đa thai Dọa sanh non - Khâu eo cổ tử cung - Chọc ối - Sinh thiết gai nhau</li></ul><h3 style="margin-left:0px;">Báo cáo hội nghị và bài báo</h3><ul><li>Báo cáo viên "Hội nghị khoa học kỹ thuật Bệnh viện Đại Học Y Dược Tp. Hồ Chí Minh"</li><li>Bài viết "Tương lai nào cho soft-marker trên siêu âm quý I" đăng trên Tạp chí Y học sinh sản số 42</li><li>Bài viết "Giá trị tiên lượng trẻ sơ sinh nhỏ so với tuổi thai dựa trên chỉ số tốc độ tăng trưởng thai qua siêu âm 2 lần ở quý 3 của thai kỳ tại Bệnh viện Hùng Vương" "TẠP CHÍ Y HỌC VIỆT NAM" 2024</li></ul>',
    _id: "68f840fadfe487238ae0a090",
    rating: {
      rate: 5,
      count: 100,
      description: "Rất tốt",
    },
    isDetailVisible: true,
    bookingTotal: 46,
    message: "",
    doctorId: "digimed_NAMNT",
    createdAt: "2025-10-22T02:27:06.733Z",
    updatedAt: "2026-01-30T02:31:39.405Z",
    __v: 32,
    seo_description:
      "Đặt khám online với bác sĩ sản phụ khoa Ngô Trung Nam: tiện lợi, nhanh chóng, ",
    seo_keyword: "bác sĩ sản phụ khoa ngô trung nam",
    slug: "bs-ngo-trung-nam",
    address: "",
    certificates:
      "<ul><li>Siêu âm sản phụ khoa khóa 14, Trường Đại học Y khoa Phạm Ngọc Thạch, 2008.&nbsp;</li><li>Thai kỳ nguy cơ cao, BV Từ Dũ, 2008.</li><li>Siêu âm thực hành sản phụ khoa khóa 1, Trường Đại học Y khoa Phạm Ngọc Thạch 2008.</li><li>Chứng chỉ siêu âm quí 1, Tổ chức y học bào thai FMF, London - Vương quốc Anh 2009</li><li>Siêu âm tổng quát khóa 19,Trường Đại học Y khoa Phạm Ngọc Thạch, 2009.</li><li>Đánh giá Kênh cổ tử cung, Tổ chức y học bào thai FMF, London - Vương quốc Anh 2010</li><li>Siêu âm Doppler, Tổ chức y học bào thai FMF, London - Vương quốc Anh 2010</li><li>Soi cổ tử cung nâng cao, Trường Đại học Y dược Tp.HCM, 2013.</li><li>Siêu âm tim thai và bệnh lý tim bẩm sinh khóa 2, Viện tim Tp.HCM, 2013.</li><li>Tầm soát ung thư cổ tử cung trong thời đại HPV, BV Hùng Vương, 2013.</li><li>Hội nghị sản phụ khoa Việt – Pháp – Châu Á – Thái Bình Dương, BV Từ Dũ cấp giấy chứng nhận, tổ chức định kỳ hàng năm</li><li>Phá thai nội khoa, BV Từ Dũ, 2014.</li><li>Phẫu thuật nội soi cơ bản trong phụ khoa, BV Từ Dũ, 2015</li><li>Đánh giá Tiền sản giật, Tổ chức y học bào thai FMF, London - Vương quốc Anh 2018</li><li>Hội nghị Sản phụ khoa Việt – Pháp – Châu Á – Thái Bình Dương lần thứ 21 2022</li><li>Hội thảo Siêu âm tim trong bệnh tim bẩm sinh: Tiếp cận theo ca lâm sàng 2022</li><li>Hội nghị khoa học công nghệ XVI 2023</li><li>Hội nghị Y học ba mẹ và thai nhi Việt – Pháp – Châu Á – Thái Bình Dương lần 16 2023</li><li>Kiểm soát nhiễm khuẩn bệnh viện 2023</li><li>Kỹ thuật siêu âm bơm nước buồng tử cung 2023</li><li>Quản lý chất lượng bệnh viện 2023</li><li>Sàng lọc và dự phòng các biến chứng thai kỳ 2023</li><li>Các tiến bộ trong chẩn đoán trước sinh và y học bào thai 2023</li><li>&nbsp;Nội tiết sinh sản và hỗ trợ sinh sản 2023</li><li>Chăm sóc toàn diện sức khỏe phụ nữ tuổi mãn kinh 2023</li><li>Tránh thai kết hợp thế hệ mới 2023</li><li>Các vấn đề mới trong nội tiết sinh sản 2023</li><li>Chẩn đoán và điều trị Hiếm muộn 2025</li></ul>",
    countryId: "",
    doctorAds: [],
    guideDoctor: [],
    iframeVideo: [],
    language: "",
    languageId: "",
    permanent_address: "",
    pricing: [],
    questions: [],
    seo: {
      _id: "6969dbe349ad68081335253e",
      faq: [],
      title: "",
      createdAt: "2026-01-16T06:34:11.674Z",
      updatedAt: "2026-01-16T06:34:11.674Z",
    },
    specialty: [],
    notiBookingTelemed:
      "Bạn đang chọn bác sĩ tư vấn qua video, nếu bạn muốn đặt khám tại cơ sở vui lòng chọn lại dịch vụ Đặt khám tại Cơ sở y tế",
  },
  partner: {
    _id: "63bbc9bdd66e020019952d1e",
    partnerId: "digimed",
    city_id: "medpro_79",
    name: "Bác sĩ Chuyên Khoa",
    image:
      "https://bo-api.medpro.com.vn:5000/static/images/digimed/web/logo.png?1673320056506?t=222222",
    address: "Tư vấn Online qua App Medpro",
    slug: "digimed",
    newHospitalTypes: [1],
    packageImgDefault: "",
    circleLogo:
      "https://bo-api.medpro.com.vn:5000/static/images/digimed/web/logo.png?1673320056506?t=222222",
    rating: 4.7,
  },
};
