import { WeeklyScheduleResponse } from "../types";

/**
 * Mock data based on real API response (test1.json).
 * Structure: Service -> TreeIds -> Day -> Shift
 * Date format: DDMMYYYY (as returned by API)
 */
export const WEEKLY_SCHEDULE_MOCK: WeeklyScheduleResponse = {
  doctorId: "bvndgiadinh_95",
  partnerId: "bvndgiadinh",
  subjectId: "bvndgiadinh_5413",
  services: [
    {
      id: "bvndgiadinh_59_1754991886524",
      name: "Khám chuyên gia",
      price: 500000,
      treeIds: [
        {
          treeId: "DATE,VIP",
          id: "bvndgiadinh_59_1754991886524",
          name: "Khám chuyên gia",
          price: 500000,
          days: [
            {
              date: "06042026",
              dayOfWeek: "Thứ 2",
              displayDate: "06/04/2026",
              timemiliseconds: "1775408400000",
              shifts: [
                {
                  timeId: "818_1_07:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "07:00",
                  endTime: "08:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_08:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "08:00",
                  endTime: "09:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_09:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "09:00",
                  endTime: "10:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_10:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "10:00",
                  endTime: "11:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
              ],
            },
            {
              date: "07042026",
              dayOfWeek: "Thứ 3",
              displayDate: "07/04/2026",
              timemiliseconds: "1775494800000",
              shifts: [
                {
                  timeId: "818_1_07:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "07:00",
                  endTime: "08:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_08:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "08:00",
                  endTime: "09:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_09:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "09:00",
                  endTime: "10:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_10:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "10:00",
                  endTime: "11:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
              ],
            },
            {
              date: "08042026",
              dayOfWeek: "Thứ 4",
              displayDate: "08/04/2026",
              timemiliseconds: "1775581200000",
              shifts: [
                {
                  timeId: "818_1_07:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "07:00",
                  endTime: "08:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_08:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "08:00",
                  endTime: "09:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_09:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "09:00",
                  endTime: "10:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_10:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "10:00",
                  endTime: "11:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
              ],
            },
            {
              date: "09042026",
              dayOfWeek: "Thứ 5",
              displayDate: "09/04/2026",
              timemiliseconds: "1775667600000",
              shifts: [
                {
                  timeId: "818_1_07:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "07:00",
                  endTime: "08:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_08:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "08:00",
                  endTime: "09:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_09:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "09:00",
                  endTime: "10:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_10:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "10:00",
                  endTime: "11:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
              ],
            },
            {
              date: "10042026",
              dayOfWeek: "Thứ 6",
              displayDate: "10/04/2026",
              timemiliseconds: "1775754000000",
              shifts: [
                {
                  timeId: "818_1_07:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "07:00",
                  endTime: "08:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_08:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "08:00",
                  endTime: "09:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_09:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "09:00",
                  endTime: "10:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_1_10:00",
                  shiftName: "Sáng",
                  shiftCode: "SHIFT_1",
                  startTime: "10:00",
                  endTime: "11:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "bvndgiadinh_59",
      name: "Khám dịch vụ - BHYT",
      price: 129400,
      treeIds: [
        {
          treeId: "VIP",
          id: "bvndgiadinh_59",
          name: "Khám dịch vụ - BHYT",
          price: 129400,
          days: [
            {
              date: "06042026",
              dayOfWeek: "Thứ 2",
              displayDate: "06/04/2026",
              timemiliseconds: "1775408400000",
              shifts: [
                {
                  timeId: "818_2_13:00",
                  shiftName: "Chiều",
                  shiftCode: "SHIFT_2",
                  startTime: "13:00",
                  endTime: "14:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_2_14:00",
                  shiftName: "Chiều",
                  shiftCode: "SHIFT_2",
                  startTime: "14:00",
                  endTime: "15:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_2_15:00",
                  shiftName: "Chiều",
                  shiftCode: "SHIFT_2",
                  startTime: "15:00",
                  endTime: "16:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
              ],
            },
            {
              date: "10042026",
              dayOfWeek: "Thứ 6",
              displayDate: "10/04/2026",
              timemiliseconds: "1775754000000",
              shifts: [
                {
                  timeId: "818_2_13:00",
                  shiftName: "Chiều",
                  shiftCode: "SHIFT_2",
                  startTime: "13:00",
                  endTime: "14:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_2_14:00",
                  shiftName: "Chiều",
                  shiftCode: "SHIFT_2",
                  startTime: "14:00",
                  endTime: "15:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
                {
                  timeId: "818_2_15:00",
                  shiftName: "Chiều",
                  shiftCode: "SHIFT_2",
                  startTime: "15:00",
                  endTime: "16:00",
                  roomId: "bvndgiadinh_818",
                  roomName: "Sảnh NT Long(NTM)",
                  status: "AVAILABLE",
                  maxSlot: 6,
                  availableSlot: 6,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
